[tool.poetry]
name = "literallyme"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
telethon = "^1.33.1"
replicate = "^0.22.0"
insightface = "^0.7.3"
python-dotenv = "^1.0.0"
mongo = "^0.2.0"
matplotlib = "^3.8.2"
seaborn = "^0.13.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

